# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-20 11:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('display_picture_url', models.CharField(max_length=200)),
                ('sub', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
